#-------------------------------------------------
#
# Project created by QtCreator 2016-12-18T00:16:58
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = sdApp
TEMPLATE = app

# turn off warnings that come from the subproject sd
QMAKE_CXXFLAGS += -w

# http://dragly.org/2013/11/05/copying-data-files-to-the-build-directory-when-working-with-qmake/
#$(COPY_DIR) – Holds a platform-dependent copy-command that makes sure to copy recursively.
#$$PWD – Holds the name of the source code directory, where your .pro file resides.
#$$OUT_PWD – Holds the name of the build directory. Note that this may not work if you are running qmake and make in the same directory as your source code, as you will be copying into the same folder as you copy from.
#copydata – Just a name we choose. You can replace this with whatever you want.
#first – This is a build step that already exists in the Makefile generated by qmake. We attach the copy build step to this build step.
#export – Makes the variable in the argument of the function available in a global scope.
#QMAKE_EXTRA_TARGETS – Tells qmake that you want to build more targets than the ones it adds by default to the Makefile.

mac: {
    # Copy the sd executable and the sd_calls.dat data file to the same place as the sdApp executable
    #  (inside sdApp.app)
    # This way, it's easy for sdApp to find the executable for sd.
    copydata.commands = $(COPY_DIR) $$PWD/../sd/sd_calls.dat $$OUT_PWD/sdApp.app/Contents/MacOS
    copydata2.commands = $(COPY_DIR) $$OUT_PWD/../sd/sd $$OUT_PWD/sdApp.app/Contents/MacOS
    first.depends = $(first) copydata copydata2
    export(first.depends)
    export(copydata.commands)
    export(copydata2.commands)
    QMAKE_EXTRA_TARGETS += first copydata copydata2
}

win32: {
    # TODO
}

unix: {
    # TODO
}

SOURCES += main.cpp\
        mainwindow.cpp \
    common.cpp \
    mapcachefile.cpp \
    sdbasic.cpp \
    sdconc.cpp \
    sdconcpt.cpp \
    sdctable.cpp \
    sdgetout.cpp \
    sdinit.cpp \
    sdistort.cpp \
    sdmain.cpp \
    sdmatch.cpp \
    sdmoves.cpp \
    sdpick.cpp \
    sdpreds.cpp \
    sdsi.cpp \
    sdtables.cpp \
    sdtand.cpp \
    sdtop.cpp \
    sdui-ttu.cpp \
    sdui-tty.cpp \
    sdutil.cpp \
    console.cpp \
    sdhighlighter.cpp \
    renderarea.cpp

HEADERS  += mainwindow.h \
    database.h \
    mapcachefile.h \
    resource.h \
    sd.h \
    sdbase.h \
    sdui.h \
    sort.h \
    console.h \
    sdhighlighter.h \
    renderarea.h \
    common.h

FORMS    += mainwindow.ui
