# Makefile for Sd/Sdtty for DJGPP / DOS

# This gives the compiler name and any switches that it needs to make
# it operate the way we want (ANSI language, standards conformance,
# target hardware, etc.)
CC = gcc

# This gives any "-D" switches that we always need to send to the compiler.
DEFS = -Wall -Wno-switch -Wno-uninitialized -Wno-char-subscripts

# This gives the optimization and/or debug info.  These flags presumably
# don't affect the semantics of the language and run-time environment, so you
# might reasonably want to change them to suit your taste.
# The options shown here have been chosen to optimize the program for
# production use.  Depending on your operating system, compiler, and debugger,
# this may compromise the ability to debug the program.  In this case, you may
# need to choose different options, typically "-g", for debugging.
# Consult your system, compiler, and debugger vendor for further information.
CDEBUGFLAGS = -O2

CFLAGS =$(CDEBUGFLAGS) $(DEFS)

# These are the "-I"  and "-D" flags that we must use for the compilation
# of the system-dependent part of the TTY user interface (sdui-tpc.cpp).
TTY_FLAGS =

# These are the library flags that we must use for the final bind of
# "sdtty".
TTY_LIBS = -lpc

# Note:  If change this list, make corresponding changes
# in pcfiles.lst.
SD_OBJS = sdmain.o sdutil.o sdbasic.o sdinit.o \
          sdtables.o sdctable.o sdtop.o sdconcpt.o sdpreds.o \
          sdgetout.o sdmoves.o sdtand.o sdconc.o sdistort.o \
          sdpick.o sdsi.o

# Note:  If change this list, make corresponding changes
# in pcfiles.lst.
SDTTY_OBJS = sdui-tty.o sdmatch.o sdui-tpc.o

# pcfiles.lst should have SD_OBJS + SDTTY_OBJS
SDTTY_LINK_OBJS = @pcfiles.lst

MKCALLS_SRCS = mkcalls.cpp dbcomp.cpp
MKCALLS_OBJS = mkcalls.o dbcomp.o

# Just "make" will make this, which is in fact everything.
all: sdtty.exe sd_calls.dat

mkcalls.exe: $(MKCALLS_OBJS)
	$(CC) $(CFLAGS) -o mkcalls.bin $(MKCALLS_OBJS)

sdtty.exe: $(SD_OBJS) $(SDTTY_OBJS)
	$(CC) $(CFLAGS) -o sdtty.bin $(SDTTY_LINK_OBJS) $(TTY_LIBS)

sd_calls.dat: sd_calls.txt mkcalls.exe
	./mkcalls ./sd_calls.txt

.c.o:
	$(CC) $(CFLAGS) -c $<

.cpp.o:
	$(CC) $(CFLAGS) -c $<

sdui-tpc.o: sdui-tpc.cpp
	$(CC) $(CFLAGS) $(TTY_FLAGS) -c $<

dbcomp.o sdmain.o sdsi.o: paths.h

dbcomp.o: database.h

$(SD_OBJS) $(SDTTY_OBJS): sd.h database.h

RM = del

clean::
	rm *.o *.bin sdtty.exe mkcalls.exe sd_calls.dat

TAG_FILES = ${SRCS} *.h

tags: ${TAG_FILES}
	/opt/sfw/bin/ctags ${TAG_FILES}
