/****************************************************************************
**
** Copyright (C) 2016, 2017, 2018 Mike Pogue, Dan Lyke
** Contact: mpogue @ zenstarstudio.com
**
** This file is part of the SquareDesk application.
**
** $SQUAREDESK_BEGIN_LICENSE$
**
** Commercial License Usage
** For commercial licensing terms and conditions, contact the authors via the
** email address above.
**
** GNU General Public License Usage
** This file may be used under the terms of the GNU
** General Public License version 2.0 or (at your option) the GNU General
** Public license version 3 or any later version approved by the KDE Free
** Qt Foundation. The licenses are as published by the Free Software
** Foundation and appear in the file LICENSE.GPL2 and LICENSE.GPL3
** included in the packaging of this file.
**
** $SQUAREDESK_END_LICENSE$
**
****************************************************************************/

#include <stdio.h>
#include <danceprograms.h>


const char *danceprogram_basic1[] = {
    " 1, Circle Left / Circle Right",
    " 2, Forward and Back",
    " 3, Dosado / Dosado to a Wave",
    " 4, Swing",
    " 5, Promenade Family",
    " 5.a, Couples (Full, 1/2, 3/4) ",
    " 5.b, Single File Promenade ",
    " 5.c, Wrong Way Promenade ",
    " 5.d, Star Promenade",
    " 6, Allemande Left",
    " 7, Arm Turns",
    " 8, Right and Left Grand Family",
    " 8.a, Right and Left Grand ",
    " 8.b, Weave the Ring",
    " 8.c, Wrong Way Grand",
    " 9, Left-Hand Star / Right-Hand Star",
    "10, Pass Thru",
    "11, Half Sashay Family",
    "11.a, Half Sashay",
    "11.b, Rollaway",
    "11.c, Ladies In, Men Sashay",
    "12, Turn Back Family ",
    "12.a, U-Turn Back",
    "12.b, Backtrack",
    "13, Separate",
    "13.a, Around 1 or 2 to a Line ",
    "13.b, Around 1 or 2 and Come Into the Middle",
    "14, Split Two",
    "15, Courtesy Turn",
    "16, Ladies Chain Family",
    "16.a, Two Ladies Chain (Reg. & 3/4) ",
    "16.b, Four Ladies Chain(Reg. & 3/4)",
    "16.c, Chain Down the Line",
    "17, Do Paso",
    "18, Lead Right",
    "19, Veer Left / Veer Right",
    "20, Bend the Line",
    "21, Circulate Family",
    "21.a, (Named Dancers) Circulate ",
    "21.b, Couples Circulate",
    "21.c, All Eight Circulate",
    "21.d, Single File Circulate",
    "21.e, Split/Box Circulate",
    "22, Right and Left Thru",
    "23, Grand Square",
    "24, Star Thru",
    "25, California Twirl",
    "26, Walk Around the Corner",
    "27, See Saw",
    "28, Square Thru (1, 2, 3, 4) / Left Square Thru (1, 2, 3, 4)",
    "29, Circle to a Line",
    "30, Dive Thru",
    NULL
};

const char *danceprogram_basic2[] = {
    "31, Wheel Around ",
    "32, Thar Family",
    "32.a, Allemande Thar",
    "32.b, Allemande Left to an Allemande Thar ",
    "32.c, Wrong Way Thar",
    "33, Slip the Clutch ",
    "34, Shoot the Star / Shoot the Star Full Around ",
    "35, Box the Gnat",
    "36, Trade Family",
    "36.a, (Named Dancers) Trade ",
    "36.b, Couples Trade",
    "36.c, Partner Trade",
    "37, Ocean Wave Family",
    "37.a, Step to a Wave",
    "37.b, Balance",
    "38, Alamo Style",
    "39, Swing Thru / Left Swing Thru ",
    "40, Run / Cross Run",
    "41, Pass the Ocean",
    "42, Extend",
    "43, Wheel and Deal",
    "44, Double Pass Thru",
    "45, First Couple Go Left/Right, Next Couple Go Left/Right ",
    "46, Zoom",
    "47, Flutterwheel / Reverse Flutterwheel",
    "48, Sweep a Quarter ",
    "49, Trade By",
    "50, Touch 1/4",
    "51, Ferris Wheel",
    NULL
};

const char *danceprogram_mainstream[] = {
    "52, Cloverleaf",
    "53, Turn Thru",
    "54, Eight Chain Thru / Eight Chain 1, 2, 3, Etc.",
    "55, Pass to the Center",
    "56, Single Hinge / Couples Hinge ",
    "57, Centers In",
    "58, Cast Off 3/4",
    "59, Spin the Top",
    "60, Walk and Dodge",
    "61, Slide Thru",
    "62, Fold / Cross Fold",
    "63, Dixie Style to an Ocean Wave ",
    "64, Spin Chain Thru",
    "65, Tag the Line (In/Out/Left/Right) ",
    "66, Half Tag",
    "67, Scoot Back",
    "68, Recycle (From a Wave Only)",
    NULL,
};

const char *danceprogram_plus[] = {
    " 1, Acey Deucey",
    " 2, Teacup Chain",
    " 3, Ping Pong Circulate",
    " 4, Load the Boat",
    " 5, Peel Off",
    " 6, Linear Cycle (From Waves Only)",
    " 7, Coordinate",
    " 8, (Anything) & Spread",
    " 9, Spin Chain the Gears",
    "10, Track II",
    "11, (Anything) & Roll",
    "12, Follow Your Neighbor",
    "13, Fan the Top",
    "14, Explode the Wave",
    "15, Explode & (Anything) (From Waves Only)",
    "16, Relay the Deucey",
    "17, Peel the Top",
    "18, Diamond Circulate",
    "19, Single Circle to a Wave",
    "20, Trade the Wave ",
    "21, Flip the Diamond",
    "22, Grand Swing Thru",
    "23, Crossfire",
    "24, All 8 Spin the Top",
    "25, Cut the Diamond",
    "26, Chase Right",
    "27, Dixie Grand",
    "28, 3/4 Tag the Line",
    "29, Spin Chain and Exchange the Gears    ",
    NULL
};
const char *danceprogram_a1[] = {
    " 1, Belles and Beaus (couples facing same direction only)",
    " 2, Brace Thru ",
    " 3, Cross Trail Thru",
    " 4, Triple Trade",
    " 5, Triple Scoot",
    " 6, Grand Follow Your Neighbor",
    " 7, Quarter Thru",
    " 8, Wheel Thru",
    " 9, Turn and Deal (2-faced lines, lines facing out)",
    "10, Pass In/Out",
    "11, Chain Reaction (1/4 tag)",
    "12, Mix",
    "13, Lockit",
    "14, Right (Left) Roll to a Wave",
    "15, Cast a Shadow",
    "16, Six-Two Acey-Deucey",
    "17, Clover and (Anything)",
    "18, Turn and Deal (ocean waves & other Lines) ",
    "19, Quarter In/Out",
    "20, Cross Over Circulate (two faced lines)",
    "21, Partner Tag",
    "22, Partner Hinge",
    "23, Horseshoe Turn",
    "24, Pass the Sea",
    "25, Split Square Thru",
    "26, Step and Slide",
    "27, Transfer the Column",
    "28, Cross Over Circulate (ocean waves & other lines)",
    "29, Swap Around",
    "30, Explode the Line",
    "31, As Couples Concept",
    "32, Ends Bend",
    "33, Square Chain Thru",
    "34, Scoot and Dodge",
    "35, Double Star Thru",
    "36, Left Wheel Thru",
    "37, (Anything) and Cross (Named Dancers) Cross",
    "38, Fractional Tops",
    "39, Three Quarter Thru",
    "40, Triple Star Thru",
    "41, Cycle and Wheel",
    "42, Grand Quarter Thru",
    "43, Grand Three Quarter Thru",
    "44, Explode and (Anything)",
    "45, Pair Off",
    "46, Reverse Swap Around",
    "47, Cross Clover and (Anything)",
    "48, Any Hand Concept",
    "49, Preface Items",
    "50, Split Square Chain Thru",
    NULL
};
const char *danceprogram_a2[] = {
    " 1, Single Wheel",
    " 2, In Roll Circulate ",
    " 3, Slip",
    " 4, Scoot and Weave",
    " 5, Split/Box Counter Rotate",
    " 6, Swing",
    " 7, Swing & Mix",
    " 8, Trade Circulate (waves only)",
    " 9, Motivate",
    "10, Switch the Wave",
    "11, Pass and Roll",
    "12, Scoot Chain Thru",
    "13, Slide",
    "14, Recycle (facing couples)",
    "15, Spin the Windmill ",
    "16, Out Roll Circulate",
    "17, Switch to a Diamond (waves only)",
    "18, Hourglass Circulate ",
    "19, Cut the Hourglass",
    "20, Flip the Hourglass",
    "21, Pass and Roll Your Neighbor",
    "22, Trade Circulate (two faced lines)",
    "23, Zig-Zag / Zag-Zig",
    "24, Checkmate the Column",
    "25, Mini-Busy",
    "26, Slither",
    "27, Trail Off",
    "28, Remake Family",
    "28.a, Remake",
    "28.b, Grand Remake",
    "28.c, Remake The Thar",
    "29, Switch to an Hourglass (waves only)",
    "30, Split / Box Transfer",
    "31, Diamond Chain Thru",
    "32, Peel & Trail (from completed DPT)",
    "33, Peel & Trail (Columns)",
    "34, Transfer and (Anything)",
    "35, All 4 Couples Concept (such as)",
    "35.a, All 4 Couples Star Thru ",
    "35.b, All 4 Right and Left Thru",
    "35.c, All 4 Chase Right",
    "36, All 8 Concept (such as) ",
    "36.a, All 8 Swing Thru",
    "36.b, All 8 Switch the Wave ",
    "36.c, All 8 Walk and Dodge",
    "36.d, All 8 Mix",
    "37, Preface Items",
    NULL
};

static const char *b1 = "b1";
static const char *b2 = "b2";
static const char *ms = "ms";
static const char *plus = "plus";
static const char *a1 = "a1";
static const char *a2 = "a2";

const struct DanceProgramCallInfo danceprogram_callinfo[] = {
    { b1, "Circle Left / Circle Right", "1/2: 4, 3/4: 6, Full: 8" },
    { b1, "forward and back", "Lines close together: 4; All others: 8" },
    { b1, "Dosado / Dosado to a Wave", "SS with corner, 6 steps; with partner, 6; from a Box formation, 6; SS across the set, 8" },
    { b1, "swing", "Variable, at least 4" },
    { b1, "Promenade Family", NULL },
    { b1, "Couples (Full, 1/2, 3/4)", "1/4: 4, 1/2: 8, 3/4: 12, Full: 16" },
    { b1, "Single File Promenade ", NULL },
    { b1, "Wrong Way Promenade ", NULL },
    { b1, "Star Promenade", "1/2: 6, 3/4: 9, Full: 12, Full plus a back out at home: 16" },
    { b1, "allemande left", "1/2 arm turn: 4-6; 3/4 arm turn: 6-8; Full arm turn: 8" },
    { b1, "Arm Turns", "1/2: 4, 3/4: 4 to 6, Full: 6 to 8" },
    { b1, "Right and Left Grand Family", "10" },
    { b1, "right and left grand", "10" },
    { b1, "weave the ring", "10" },
    { b1, "wrong way grand", "10" },
    { b1, "Left-Hand Star / Right-Hand Star", "1/2: 4, 3/4: 6, Full: 8" },
    { b1, "pass thru", "2" },
    { b1, "half sashay family", "4" },
    { b1, "half sashay", "4" },
    { b1, "rollaway", "4" },
    { b1, "ladies in, men sashay", "4" },
    { b1, "turn back family ", "2" },
    { b1, "u-turn back", "2" },
    { b1, "backtrack", "2" },
    { b1, "separate", "2, or determined by the distance traveled around the outside" },
    { b1, "around 1 or 2 to a line ", "Heads Pass Thru; Separate Around 1 To A Line: 8, Heads Pass Thru; Separate Around 2 To A Line: 10" },
    { b1, "Around 1 or 2 and Come Into the Middle", NULL },
    { b1, "split two", "2" },
    { b1, "courtesy turn", "4" },
    { b1, "ladies chain family", "Facing Couples 6; Squared Set: 8" },
    { b1, "two ladies chain (reg. & 3/4) ", "Facing Couples: 6; Squared Set: 8" },
    { b1, "Four Ladies Chain(Reg. & 3/4)", "Regular 8; 3/4: 10" },
    { b1, "chain down the line", "8" },
    { b1, "do paso", "12" },
    { b1, "lead right", "4" },
    { b1, "veer left / veer right", "2" },
    { b1, "veer", "2" },
    { b1, "bend the line", "4" },
    { b1, "circulate family", "Single File Circulate, 2; all other circulates, 4" },
    { b1, "(Named Dancers) Circulate ", "4" },
    { b1, "Couples Circulate", "4" },
    { b1, "All Eight Circulate", "4" },
    { b1, "Single File Circulate", "2" },
    { b1, "Split/Box Circulate", "4" },
    { b1, "right and left thru", "SS, 8: Box or Ocean Wave, 6" },
    { b1, "grand square", "32" },
    { b1, "star thru", "4" },
    { b1, "california twirl", "4" },
    { b1, "walk around the corner", "8" },
    { b1, "see saw", "8" },
    { b1, "square thru (1, 2, 3, 4) / left square thru (1, 2, 3, 4)", "1: 2, 2: 5, 3: 7 or 8, 4: 10" },
    { b1, "circle to a line", "8" },
    { b1, "dive thru", "Couple diving under: 2, couple making the arch: 6" },
    { b2, "wheel around ", "4" },
    { b2, "thar family", NULL },
    { b2, "allemande thar", "2 (for the Left Arm Turn 1/2)" },
    { b2, "allemande left to an allemande thar", "12" },
    { b2, "wrong way thar", "2 (for the Right Arm Turn 1/2)" },
    { b2, "slip the clutch ", "2" },
    { b2, "shoot the star / shoot the star full around ", "4; full around: 6" },
    { b2, "box the gnat", "4" },
    { b2, "trade family", NULL },
    { b2, "(Named Dancers) Trade ", "3, with additional beats for non-adjacent dancers" },
    { b2, "couples trade", "4" },
    { b2, "partner trade", "3" },
    { b2, "ocean wave family", NULL },
    { b2, "step to a wave", "2" },
    { b2, "balance", "4" },
    { b2, "alamo style", "4" },
    { b2, "swing thru / left swing thru ", "6" },
    { b2, "run / cross run", "4; 6" },
    { b2, "pass the ocean", "4" },
    { b2, "extend", "2" },
    { b2, "wheel and deal", "4" },
    { b2, "double pass thru", "4 steps." },
    { b2, "first couple go left/right, next couple go left/right", "6" },
    { b2, "zoom", "4" },
    { b2, "flutterwheel / reverse flutterwheel", "8 (SS All four ladies, 12 steps)" },
    { b2, "sweep a quarter", "2 couples, 2 steps; all 4 couples, 4 steps." },
    { b2, "trade by", "4 steps." },
    { b2, "touch 1/4", "2" },
    { b2, "touch a quarter", "2" },
    { b2, "ferris wheel", "6" },
    { ms, "cloverleaf", "8" },
    { ms, "turn thru", "4" },
    { ms, "eight chain thru / eight chain 1, 2, 3, etc.", "20; each odd-numbered part: 2; each even-numbered part: 3" },
    { ms, "pass to the center", "Dancers who finish in the center: 2. Dancers who finish on the ends: 6." },
    { ms, "single hinge / couples hinge ", "2 steps, 3 steps" },
    { ms, "centers in", "2" },
    { ms, "cast off 3/4", "6" },
    { ms, "cast off three quarters", "6" },
    { ms, "spin the top", "8" },
    { ms, "walk and dodge", "4 steps." },
    { ms, "slide thru", "4" },
    { ms, "fold / cross fold", "2; 4" },
    { ms, "dixie style to an ocean wave ", "6; all 4 couples 8" },
    { ms, "spin chain thru", "16 steps" },
    { ms, "tag the line (in/out/left/right) ", "6" },
    { ms, "half tag", "4 steps" },
    { ms, "scoot back", "6 steps" },
    { ms, "recycle (from a wave only)", "4" },
    { plus, "acey deucey", "4" },
    { plus, "teacup chain", "32" },
    { plus, "ping pong circulate", "6" },
    { plus, "load the boat", "12" },
    { plus, "peel off", "4" },
    { plus, "linear cycle (from waves only)", "8-10" },
    { plus, "coordinate", "8" },
    { plus, "(anything) & spread", "2" },
    { plus, "spin chain the gears", "24" },
    { plus, "track ii", "8" },
    { plus, "(anything) & roll", "2" },
    { plus, "follow your neighbor", "6" },
    { plus, "fan the top", "4" },
    { plus, "explode the wave", "6" },
    { plus, "explode & (anything) (from waves only)", "2" },
    { plus, "relay the deucey", "20" },
    { plus, "peel the top", "6" },
    { plus, "diamond circulate", "3" },
    { plus, "single circle to a wave", "4" },
    { plus, "trade the wave ", "6" },
    { plus, "flip the diamond", "3" },
    { plus, "grand swing thru", "6" },
    { plus, "crossfire", "6" },
    { plus, "all 8 spin the top", "10" },
    { plus, "cut the diamond", "6" },
    { plus, "chase right", "6" },
    { plus, "dixie grand", "6" },
    { plus, "3/4 tag the line", "5" },
    { plus, "spin chain and exchange the gears", "26" },
    { a1, "belles and beaus (couples facing same direction only)", NULL },
    { a1, "brace thru", "6, SS 8" },
    { a1, "cross trail thru", "6, SS 6" },
    { a1, "triple trade", "4" },
    { a1, "triple scoot", "6" },
    { a1, "grand follow your neighbor", "6" },
    { a1, "quarter thru", "6" },
    { a1, "wheel thru", "4, SS 6" },
    { a1, "turn and deal (2-faced lines, lines facing out)", "4" },
    { a1, "pass in/out", "4" },
    { a1, "chain reaction (1/4 tag)", "12" },
    { a1, "mix", "6" },
    { a1, "lockit", "4" },
    { a1, "right (left) roll to a wave", "4 & 2" },
    { a1, "cast a shadow", "10" },
    { a1, "six-two acey-deucey", "4" },
    { a1, "clover and (anything)", "Greater of 4 or the call" },
    { a1, "turn and deal (ocean waves & other lines)", "4" },
    { a1, "quarter in/out", "2" },
    { a1, "cross over circulate (two faced lines)", "6" },
    { a1, "partner tag", "3" },
    { a1, "partner hinge", "2" },
    { a1, "horseshoe turn", "6" },
    { a1, "pass the sea", "6" },
    { a1, "split square thru", "6-8-10, SS 8-10-12" },
    { a1, "step and slide", "4" },
    { a1, "transfer the column", "10" },
    { a1, "cross over circulate (ocean waves & other lines)", "6" },
    { a1, "swap around", "4" },
    { a1, "explode the line", "6" },
    { a1, "as couples concept", NULL },
    { a1, "ends bend", "2" },
    { a1, "square chain thru", "14" },
    { a1, "scoot and dodge", "8" },
    { a1, "double star thru", "6" },
    { a1, "left wheel thru", "4, SS 6" },
    { a1, "(anything) and cross (named dancers) cross", "call + 2" },
    { a1, "fractional tops", "4-6-8" },
    { a1, "three quarter thru", "8" },
    { a1, "triple star thru", "10" },
    { a1, "cycle and wheel", "4" },
    { a1, "grand quarter thru", "6" },
    { a1, "grand three quarter thru", "8" },
    { a1, "explode and (anything)", "2 + call" },
    { a1, "pair off", "2, SS 4" },
    { a1, "reverse swap around", "4" },
    { a1, "cross clover and (anything)", "greater of 10 or the call" },
    { a1, "any hand concept", NULL },
    { a1, "split square chain thru", "12" },
    { a2, "single wheel", "4" },
    { a2, "in roll circulate", "4" },
    { a2, "slip", "3" },
    { a2, "scoot and weave", "10" },
    { a2, "split/box counter rotate", "4" },
    { a2, "swing", "3" },
    { a2, "swing & mix", "8" },
    { a2, "trade circulate (waves only)", "6" },
    { a2, "motivate", "16" },
    { a2, "switch the wave", "6" },
    { a2, "pass and roll", "10" },
    { a2, "scoot chain thru", "12" },
    { a2, "slide", "3" },
    { a2, "recycle (facing couples)", "6" },
    { a2, "spin the windmill", "12" },
    { a2, "out roll circulate", "6" },
    { a2, "switch to a diamond (waves only)", "4" },
    { a2, "hourglass circulate", "4" },
    { a2, "cut the hourglass", "6" },
    { a2, "flip the hourglass", "4" },
    { a2, "pass and roll your neighbor", "12" },
    { a2, "trade circulate (two faced lines)", "6" },
    { a2, "zig-zag / zag-zig", "2" },
    { a2, "checkmate the column", "10" },
    { a2, "mini-busy", "6" },
    { a2, "slither", "3" },
    { a2, "trail off", "6" },
    { a2, "remake family", NULL },
    { a2, "remake", "Alamo 12, others 10" },
    { a2, "grand remake", "10" },
    { a2, "remake the thar", "10" },
    { a2, "switch to an hourglass (waves only)", "4" },
    { a2, "split / box transfer", "8" },
    { a2, "diamond chain thru", "10" },
    { a2, "peel & trail (from completed dpt)", "4" },
    { a2, "peel & trail (columns)", "6" },
    { a2, "transfer and (anything)", "8 (any starts on 5)" },
    { a2, "all 4 couples concept (such as)", NULL },
    { a2, "All 4 Couples Star Thru", "6" },
    { a2, "All 4 Right and Left Thru", "10" },
    { a2, "All 4 Chase Right", "10" },
    { a2, "All 8 Concept (such as)", NULL },
    { a2, "All 8 Swing Thru", "8" },
    { a2, "All 8 Switch the Wave", NULL },
    { a2, "All 8 Walk and Dodge", "6" },
    { a2, "All 8 Mix", NULL },
    { NULL, NULL, NULL }
};
