#!/bin/bash
# Get all new VAMP files (ARM64) from /opt/homebrew
# See Issue #1039
#
# ****** MODIFY LINE 7 FOR YOUR SETUP ******

export VAMPPLUGINSDKDIR=/Users/mpogue/Downloads/vamp-plugin-sdk-master
export DEVROOTDIR=/Users/mpogue/clean3/SquareDesk/SquareDesk-DEV
export VAMPDIR=${DEVROOTDIR}/local_macosx/vamp
export CLEANFILESDIR=${VAMPDIR}/cleanVAMPfiles

echo "======================="
echo Getting a new copy of vamp-simple-host from ${VAMPPLUGINSDKDIR}....
rm ${CLEANFILESDIR}/vamp-simple-host
cp ${VAMPPLUGINSDKDIR}/build/vamp-simple-host ${CLEANFILESDIR}

echo Getting new copies of the dependent dylibs from /opt/homebrew/opt....
rm ${CLEANFILESDIR}/*.dylib

cp /opt/homebrew/opt/libsndfile/lib/libsndfile.1.dylib ${CLEANFILESDIR}
cp /opt/homebrew/opt/flac/lib/libFLAC.14.dylib ${CLEANFILESDIR}
cp /opt/homebrew/opt/lame/lib/libmp3lame.0.dylib ${CLEANFILESDIR}
cp /opt/homebrew/opt/mpg123/lib/libmpg123.0.dylib ${CLEANFILESDIR}
cp /opt/homebrew/opt/libogg/lib/libogg.0.dylib ${CLEANFILESDIR}
cp /opt/homebrew/opt/opus/lib/libopus.0.dylib ${CLEANFILESDIR}
cp /opt/homebrew/opt/libvorbis/lib/libvorbis.0.dylib ${CLEANFILESDIR}
cp /opt/homebrew/opt/libvorbis/lib/libvorbisenc.2.dylib ${CLEANFILESDIR}

echo "====================="
echo Getting Queen Mary plugins and segmentino...

cp /Users/mpogue/Library/Audio/Plug-Ins/Vamp/segmentino.dylib ${CLEANFILESDIR}
cp /Users/mpogue/Library/Audio/Plug-Ins/Vamp/qm-vamp-plugins.dylib ${CLEANFILESDIR}

echo "====================="
echo DONE.
echo
