#! /bin/zsh

set -e	# exit if error encountered

# Obtain from from https://github.com/mpogue2/SquareDesk/issues/1372#issuecomment-2853201956
# these 4 files:
#	JUCE_splitaa.zip
#	JUCE_splitab.zip
#	libJUCE_splitaaa.zip = latest libJUCEstatic, that contains VST2/3 support, and projucer file to make the lib
#	libJUCE_splitaab.zip
# 

# cd to an empty temp directory
test -d temp && rm -fr temp
mkdir temp
cd temp

if [ -d /Applications/JUCE ]; then
    echo >&2 /Applications/JUCE already exists
else
    curl -fsSL -o JUCE_splitaa https://github.com/user-attachments/files/20052700/JUCE_splitaa.zip
    curl -fsSL -o JUCE_splitab https://github.com/user-attachments/files/20052703/JUCE_splitab.zip
    cat JUCE_splitaa JUCE_splitab > JUCE.zip
    unzip JUCE.zip
    mv -v JUCE /Applications/
fi

if [ -d ~/JUCEProjects ] ; then
    echo >&2 ~/JUCEProjects already exists
else
    curl -fsSL -o libJUCE_splitaaa https://github.com/user-attachments/files/20052724/libJUCE_splitaaa.zip
    curl -fsSL -o libJUCE_splitaab https://github.com/user-attachments/files/20052723/libJUCE_splitaab.zip
    cat libJUCE_splitaaa libJUCE_splitaab > libJUCE.zip
    unzip libJUCE.zip
    mkdir -p ~/JUCEProjects
    mv -v libJUCEstatic ~/JUCEProjects/
fi

cd ..
rm -fr temp
