#! /bin/zsh
# set -v
set -e	# exit if error encountered

# Obtain from from https://github.com/mpogue2/SquareDesk/issues/1372#issuecomment-2853201956
# these 4 files:
#	JUCE_splitaa.zip
#	JUCE_splitab.zip
#	libJUCE_splitaa.zip
#	libJUCE_splitab.zip
# 

test -d temp || mkdir temp
cd temp

if [ -d /Applications/JUCE ]; then
    echo >&2 /Applications/JUCE already exists
else
    curl -fsSL -o JUCE_splitaa https://github.com/user-attachments/files/20052700/JUCE_splitaa.zip
    curl -fsSL -o JUCE_splitab https://github.com/user-attachments/files/20052703/JUCE_splitab.zip
    cat JUCE_splitaa JUCE_splitab > JUCE.zip
    unzip JUCE.zip
    mv -v JUCE /Applications/
fi

if [ -d ~/JUCEProjects ] ; then
    echo >&2 ~/JUCEProjects already exists
else
    curl -fsSL -o libJUCE_splitaa https://github.com/user-attachments/files/20052724/libJUCE_splitaa.zip
    curl -fsSL -o libJUCE_splitab https://github.com/user-attachments/files/20052723/libJUCE_splitab.zip
    cat libJUCE_splitaa libJUCE_splitab > libJUCE.zip
    unzip libJUCE.zip
    mkdir -p ~/JUCEProjects
    mv -v libJUCEstatic ~/JUCEProjects/
fi

cd ..
rm -I -r temp



