# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

# DO NOT USE THIS FOR BUILDING.  Please see README_SQUAREDESK.TXT for
# THE BUILD INSTRUCTIONS. It's a one-time build to make the two static libraries.

#TARGET = kfr

#QT = core gui widgets

HEADERS = \
   $$PWD/build/kfr_config.h \
   $$PWD/include/kfr/base/basic_expressions.hpp \
   $$PWD/include/kfr/base/conversion.hpp \
   $$PWD/include/kfr/base/expression.hpp \
   $$PWD/include/kfr/base/filter.hpp \
   $$PWD/include/kfr/base/fraction.hpp \
   $$PWD/include/kfr/base/function_expressions.hpp \
   $$PWD/include/kfr/base/generators.hpp \
   $$PWD/include/kfr/base/memory.hpp \
   $$PWD/include/kfr/base/pointer.hpp \
   $$PWD/include/kfr/base/random.hpp \
   $$PWD/include/kfr/base/reduce.hpp \
   $$PWD/include/kfr/base/small_buffer.hpp \
   $$PWD/include/kfr/base/sort.hpp \
   $$PWD/include/kfr/base/univector.hpp \
   $$PWD/include/kfr/cometa/array.hpp \
   $$PWD/include/kfr/cometa/cstring.hpp \
   $$PWD/include/kfr/cometa/ctti.hpp \
   $$PWD/include/kfr/cometa/function.hpp \
   $$PWD/include/kfr/cometa/memory.hpp \
   $$PWD/include/kfr/cometa/named_arg.hpp \
   $$PWD/include/kfr/cometa/numeric.hpp \
   $$PWD/include/kfr/cometa/range.hpp \
   $$PWD/include/kfr/cometa/result.hpp \
   $$PWD/include/kfr/cometa/string.hpp \
   $$PWD/include/kfr/cometa/tuple.hpp \
   $$PWD/include/kfr/dft/data/bitrev.hpp \
   $$PWD/include/kfr/dft/data/sincos.hpp \
   $$PWD/include/kfr/dft/impl/bitrev.hpp \
   $$PWD/include/kfr/dft/impl/dft-fft.hpp \
   $$PWD/include/kfr/dft/impl/dft-impl.hpp \
   $$PWD/include/kfr/dft/impl/dft-templates.hpp \
   $$PWD/include/kfr/dft/impl/fft-impl.hpp \
   $$PWD/include/kfr/dft/impl/fft-templates.hpp \
   $$PWD/include/kfr/dft/impl/ft.hpp \
   $$PWD/include/kfr/dft/cache.hpp \
   $$PWD/include/kfr/dft/convolution.hpp \
   $$PWD/include/kfr/dft/fft.hpp \
   $$PWD/include/kfr/dft/reference_dft.hpp \
   $$PWD/include/kfr/dsp/biquad.hpp \
   $$PWD/include/kfr/dsp/biquad_design.hpp \
   $$PWD/include/kfr/dsp/dcremove.hpp \
   $$PWD/include/kfr/dsp/delay.hpp \
   $$PWD/include/kfr/dsp/ebu.hpp \
   $$PWD/include/kfr/dsp/fir.hpp \
   $$PWD/include/kfr/dsp/fir_design.hpp \
   $$PWD/include/kfr/dsp/fracdelay.hpp \
   $$PWD/include/kfr/dsp/goertzel.hpp \
   $$PWD/include/kfr/dsp/iir_design.hpp \
   $$PWD/include/kfr/dsp/mixdown.hpp \
   $$PWD/include/kfr/dsp/oscillators.hpp \
   $$PWD/include/kfr/dsp/sample_rate_conversion.hpp \
   $$PWD/include/kfr/dsp/speaker.hpp \
   $$PWD/include/kfr/dsp/special.hpp \
   $$PWD/include/kfr/dsp/state_holder.hpp \
   $$PWD/include/kfr/dsp/units.hpp \
   $$PWD/include/kfr/dsp/waveshaper.hpp \
   $$PWD/include/kfr/dsp/weighting.hpp \
   $$PWD/include/kfr/dsp/window.hpp \
   $$PWD/include/kfr/graphics/color.hpp \
   $$PWD/include/kfr/graphics/geometry.hpp \
   $$PWD/include/kfr/graphics/scaled.hpp \
   $$PWD/include/kfr/io/dr/dr_flac.h \
   $$PWD/include/kfr/io/dr/dr_mp3.h \
   $$PWD/include/kfr/io/dr/dr_wav.h \
   $$PWD/include/kfr/io/audiofile.hpp \
   $$PWD/include/kfr/io/file.hpp \
   $$PWD/include/kfr/io/python_plot.hpp \
   $$PWD/include/kfr/io/tostring.hpp \
   $$PWD/include/kfr/math/impl/abs.hpp \
   $$PWD/include/kfr/math/impl/asin_acos.hpp \
   $$PWD/include/kfr/math/impl/atan.hpp \
   $$PWD/include/kfr/math/impl/clamp.hpp \
   $$PWD/include/kfr/math/impl/gamma.hpp \
   $$PWD/include/kfr/math/impl/hyperbolic.hpp \
   $$PWD/include/kfr/math/impl/log_exp.hpp \
   $$PWD/include/kfr/math/impl/logical.hpp \
   $$PWD/include/kfr/math/impl/min_max.hpp \
   $$PWD/include/kfr/math/impl/modzerobessel.hpp \
   $$PWD/include/kfr/math/impl/round.hpp \
   $$PWD/include/kfr/math/impl/saturation.hpp \
   $$PWD/include/kfr/math/impl/select.hpp \
   $$PWD/include/kfr/math/impl/sin_cos.hpp \
   $$PWD/include/kfr/math/impl/sqrt.hpp \
   $$PWD/include/kfr/math/impl/tan.hpp \
   $$PWD/include/kfr/math/abs.hpp \
   $$PWD/include/kfr/math/asin_acos.hpp \
   $$PWD/include/kfr/math/atan.hpp \
   $$PWD/include/kfr/math/clamp.hpp \
   $$PWD/include/kfr/math/compiletime.hpp \
   $$PWD/include/kfr/math/complex_math.hpp \
   $$PWD/include/kfr/math/gamma.hpp \
   $$PWD/include/kfr/math/hyperbolic.hpp \
   $$PWD/include/kfr/math/interpolation.hpp \
   $$PWD/include/kfr/math/log_exp.hpp \
   $$PWD/include/kfr/math/logical.hpp \
   $$PWD/include/kfr/math/min_max.hpp \
   $$PWD/include/kfr/math/modzerobessel.hpp \
   $$PWD/include/kfr/math/round.hpp \
   $$PWD/include/kfr/math/saturation.hpp \
   $$PWD/include/kfr/math/select.hpp \
   $$PWD/include/kfr/math/sin_cos.hpp \
   $$PWD/include/kfr/math/sqrt.hpp \
   $$PWD/include/kfr/math/tan.hpp \
   $$PWD/include/kfr/runtime/cpuid.hpp \
   $$PWD/include/kfr/runtime/cpuid_auto.hpp \
   $$PWD/include/kfr/simd/impl/backend.hpp \
   $$PWD/include/kfr/simd/impl/backend_clang.hpp \
   $$PWD/include/kfr/simd/impl/backend_generic.hpp \
   $$PWD/include/kfr/simd/impl/basicoperators_clang.hpp \
   $$PWD/include/kfr/simd/impl/basicoperators_generic.hpp \
   $$PWD/include/kfr/simd/impl/function.hpp \
   $$PWD/include/kfr/simd/impl/intrinsics.h \
   $$PWD/include/kfr/simd/impl/operators.hpp \
   $$PWD/include/kfr/simd/impl/read_write.hpp \
   $$PWD/include/kfr/simd/impl/simd.hpp \
   $$PWD/include/kfr/simd/impl/specialconstants.hpp \
   $$PWD/include/kfr/simd/impl/specializations.i \
   $$PWD/include/kfr/simd/comparison.hpp \
   $$PWD/include/kfr/simd/complex.hpp \
   $$PWD/include/kfr/simd/constants.hpp \
   $$PWD/include/kfr/simd/digitreverse.hpp \
   $$PWD/include/kfr/simd/horizontal.hpp \
   $$PWD/include/kfr/simd/mask.hpp \
   $$PWD/include/kfr/simd/operators.hpp \
   $$PWD/include/kfr/simd/platform.hpp \
   $$PWD/include/kfr/simd/read_write.hpp \
   $$PWD/include/kfr/simd/shuffle.hpp \
   $$PWD/include/kfr/simd/types.hpp \
   $$PWD/include/kfr/simd/vec.hpp \
   $$PWD/include/kfr/testo/assert.hpp \
   $$PWD/include/kfr/testo/comparison.hpp \
   $$PWD/include/kfr/testo/console_colors.hpp \
   $$PWD/include/kfr/testo/double_double.hpp \
   $$PWD/include/kfr/testo/testo.hpp \
   $$PWD/include/kfr/all.hpp \
   $$PWD/include/kfr/base.hpp \
   $$PWD/include/kfr/capi.h \
   $$PWD/include/kfr/cident.h \
   $$PWD/include/kfr/cometa.hpp \
   $$PWD/include/kfr/config.h \
   $$PWD/include/kfr/dft.hpp \
   $$PWD/include/kfr/dsp.hpp \
   $$PWD/include/kfr/graphics.hpp \
   $$PWD/include/kfr/io.hpp \
   $$PWD/include/kfr/kfr.h \
   $$PWD/include/kfr/math.hpp \
   $$PWD/include/kfr/runtime.hpp \
   $$PWD/include/kfr/simd.hpp \
   $$PWD/include/kfr/version.hpp \
   $$PWD/tests/mpfr/mpfrplus.hpp \
   $$PWD/tests/numeric_tests.hpp

SOURCES = \
   $$PWD/build/bin/biquads \
   $$PWD/build/bin/ccv \
   $$PWD/build/bin/dft \
   $$PWD/build/bin/dft_test \
   $$PWD/build/bin/fir \
   $$PWD/build/bin/iir \
   $$PWD/build/bin/sample_rate_conversion \
   $$PWD/build/bin/window \
   $$PWD/build/cmake/cmake_uninstall.cmake \
   $$PWD/build/CMakeFiles/3.22.0-rc2/CompilerIdCXX/CMakeCXXCompilerId.cpp \
   $$PWD/build/CMakeFiles/3.22.0-rc2/CMakeCXXCompiler.cmake \
   $$PWD/build/CMakeFiles/3.22.0-rc2/CMakeDetermineCompilerABI_CXX.bin \
   $$PWD/build/CMakeFiles/3.22.0-rc2/CMakeSystem.cmake \
   $$PWD/build/CMakeFiles/kfr_dft.dir/include/kfr/dft/impl/convolution-impl.cpp.o.d \
   $$PWD/build/CMakeFiles/kfr_dft.dir/include/kfr/dft/impl/dft-impl-f32.cpp.o.d \
   $$PWD/build/CMakeFiles/kfr_dft.dir/include/kfr/dft/impl/dft-impl-f64.cpp.o.d \
   $$PWD/build/CMakeFiles/kfr_dft.dir/include/kfr/dft/impl/fft-impl-f32.cpp.o.d \
   $$PWD/build/CMakeFiles/kfr_dft.dir/include/kfr/dft/impl/fft-impl-f64.cpp.o.d \
   $$PWD/build/CMakeFiles/kfr_dft.dir/build.make \
   $$PWD/build/CMakeFiles/kfr_dft.dir/cmake_clean.cmake \
   $$PWD/build/CMakeFiles/kfr_dft.dir/cmake_clean_target.cmake \
   $$PWD/build/CMakeFiles/kfr_dft.dir/compiler_depend.internal \
   $$PWD/build/CMakeFiles/kfr_dft.dir/compiler_depend.make \
   $$PWD/build/CMakeFiles/kfr_dft.dir/compiler_depend.ts \
   $$PWD/build/CMakeFiles/kfr_dft.dir/depend.make \
   $$PWD/build/CMakeFiles/kfr_dft.dir/DependInfo.cmake \
   $$PWD/build/CMakeFiles/kfr_dft.dir/flags.make \
   $$PWD/build/CMakeFiles/kfr_dft.dir/link.txt \
   $$PWD/build/CMakeFiles/kfr_dft.dir/progress.make \
   $$PWD/build/CMakeFiles/kfr_io.dir/include/kfr/io/impl/audiofile-impl.cpp.o.d \
   $$PWD/build/CMakeFiles/kfr_io.dir/build.make \
   $$PWD/build/CMakeFiles/kfr_io.dir/cmake_clean.cmake \
   $$PWD/build/CMakeFiles/kfr_io.dir/cmake_clean_target.cmake \
   $$PWD/build/CMakeFiles/kfr_io.dir/compiler_depend.internal \
   $$PWD/build/CMakeFiles/kfr_io.dir/compiler_depend.make \
   $$PWD/build/CMakeFiles/kfr_io.dir/compiler_depend.ts \
   $$PWD/build/CMakeFiles/kfr_io.dir/depend.make \
   $$PWD/build/CMakeFiles/kfr_io.dir/DependInfo.cmake \
   $$PWD/build/CMakeFiles/kfr_io.dir/flags.make \
   $$PWD/build/CMakeFiles/kfr_io.dir/link.txt \
   $$PWD/build/CMakeFiles/kfr_io.dir/progress.make \
   $$PWD/build/CMakeFiles/uninstall.dir/build.make \
   $$PWD/build/CMakeFiles/uninstall.dir/cmake_clean.cmake \
   $$PWD/build/CMakeFiles/uninstall.dir/compiler_depend.make \
   $$PWD/build/CMakeFiles/uninstall.dir/compiler_depend.ts \
   $$PWD/build/CMakeFiles/uninstall.dir/DependInfo.cmake \
   $$PWD/build/CMakeFiles/uninstall.dir/progress.make \
   $$PWD/build/CMakeFiles/cmake.check_cache \
   $$PWD/build/CMakeFiles/CMakeDirectoryInformation.cmake \
   $$PWD/build/CMakeFiles/CMakeError.log \
   $$PWD/build/CMakeFiles/CMakeOutput.log \
   $$PWD/build/CMakeFiles/CMakeRuleHashes.txt \
   $$PWD/build/CMakeFiles/progress.marks \
   $$PWD/build/CMakeFiles/TargetDirectories.txt \
   $$PWD/build/examples/CMakeFiles/biquads.dir/biquads.cpp.o.d \
   $$PWD/build/examples/CMakeFiles/biquads.dir/build.make \
   $$PWD/build/examples/CMakeFiles/biquads.dir/cmake_clean.cmake \
   $$PWD/build/examples/CMakeFiles/biquads.dir/compiler_depend.make \
   $$PWD/build/examples/CMakeFiles/biquads.dir/compiler_depend.ts \
   $$PWD/build/examples/CMakeFiles/biquads.dir/depend.make \
   $$PWD/build/examples/CMakeFiles/biquads.dir/DependInfo.cmake \
   $$PWD/build/examples/CMakeFiles/biquads.dir/flags.make \
   $$PWD/build/examples/CMakeFiles/biquads.dir/link.txt \
   $$PWD/build/examples/CMakeFiles/biquads.dir/progress.make \
   $$PWD/build/examples/CMakeFiles/ccv.dir/build.make \
   $$PWD/build/examples/CMakeFiles/ccv.dir/ccv.cpp.o.d \
   $$PWD/build/examples/CMakeFiles/ccv.dir/cmake_clean.cmake \
   $$PWD/build/examples/CMakeFiles/ccv.dir/compiler_depend.make \
   $$PWD/build/examples/CMakeFiles/ccv.dir/compiler_depend.ts \
   $$PWD/build/examples/CMakeFiles/ccv.dir/depend.make \
   $$PWD/build/examples/CMakeFiles/ccv.dir/DependInfo.cmake \
   $$PWD/build/examples/CMakeFiles/ccv.dir/flags.make \
   $$PWD/build/examples/CMakeFiles/ccv.dir/link.txt \
   $$PWD/build/examples/CMakeFiles/ccv.dir/progress.make \
   $$PWD/build/examples/CMakeFiles/dft.dir/build.make \
   $$PWD/build/examples/CMakeFiles/dft.dir/cmake_clean.cmake \
   $$PWD/build/examples/CMakeFiles/dft.dir/compiler_depend.make \
   $$PWD/build/examples/CMakeFiles/dft.dir/compiler_depend.ts \
   $$PWD/build/examples/CMakeFiles/dft.dir/depend.make \
   $$PWD/build/examples/CMakeFiles/dft.dir/DependInfo.cmake \
   $$PWD/build/examples/CMakeFiles/dft.dir/dft.cpp.o.d \
   $$PWD/build/examples/CMakeFiles/dft.dir/flags.make \
   $$PWD/build/examples/CMakeFiles/dft.dir/link.txt \
   $$PWD/build/examples/CMakeFiles/dft.dir/progress.make \
   $$PWD/build/examples/CMakeFiles/fir.dir/build.make \
   $$PWD/build/examples/CMakeFiles/fir.dir/cmake_clean.cmake \
   $$PWD/build/examples/CMakeFiles/fir.dir/compiler_depend.make \
   $$PWD/build/examples/CMakeFiles/fir.dir/compiler_depend.ts \
   $$PWD/build/examples/CMakeFiles/fir.dir/depend.make \
   $$PWD/build/examples/CMakeFiles/fir.dir/DependInfo.cmake \
   $$PWD/build/examples/CMakeFiles/fir.dir/fir.cpp.o.d \
   $$PWD/build/examples/CMakeFiles/fir.dir/flags.make \
   $$PWD/build/examples/CMakeFiles/fir.dir/link.txt \
   $$PWD/build/examples/CMakeFiles/fir.dir/progress.make \
   $$PWD/build/examples/CMakeFiles/iir.dir/build.make \
   $$PWD/build/examples/CMakeFiles/iir.dir/cmake_clean.cmake \
   $$PWD/build/examples/CMakeFiles/iir.dir/compiler_depend.make \
   $$PWD/build/examples/CMakeFiles/iir.dir/compiler_depend.ts \
   $$PWD/build/examples/CMakeFiles/iir.dir/depend.make \
   $$PWD/build/examples/CMakeFiles/iir.dir/DependInfo.cmake \
   $$PWD/build/examples/CMakeFiles/iir.dir/flags.make \
   $$PWD/build/examples/CMakeFiles/iir.dir/iir.cpp.o.d \
   $$PWD/build/examples/CMakeFiles/iir.dir/link.txt \
   $$PWD/build/examples/CMakeFiles/iir.dir/progress.make \
   $$PWD/build/examples/CMakeFiles/sample_rate_conversion.dir/build.make \
   $$PWD/build/examples/CMakeFiles/sample_rate_conversion.dir/cmake_clean.cmake \
   $$PWD/build/examples/CMakeFiles/sample_rate_conversion.dir/compiler_depend.make \
   $$PWD/build/examples/CMakeFiles/sample_rate_conversion.dir/compiler_depend.ts \
   $$PWD/build/examples/CMakeFiles/sample_rate_conversion.dir/depend.make \
   $$PWD/build/examples/CMakeFiles/sample_rate_conversion.dir/DependInfo.cmake \
   $$PWD/build/examples/CMakeFiles/sample_rate_conversion.dir/flags.make \
   $$PWD/build/examples/CMakeFiles/sample_rate_conversion.dir/link.txt \
   $$PWD/build/examples/CMakeFiles/sample_rate_conversion.dir/progress.make \
   $$PWD/build/examples/CMakeFiles/sample_rate_conversion.dir/sample_rate_conversion.cpp.o.d \
   $$PWD/build/examples/CMakeFiles/window.dir/build.make \
   $$PWD/build/examples/CMakeFiles/window.dir/cmake_clean.cmake \
   $$PWD/build/examples/CMakeFiles/window.dir/compiler_depend.make \
   $$PWD/build/examples/CMakeFiles/window.dir/compiler_depend.ts \
   $$PWD/build/examples/CMakeFiles/window.dir/depend.make \
   $$PWD/build/examples/CMakeFiles/window.dir/DependInfo.cmake \
   $$PWD/build/examples/CMakeFiles/window.dir/flags.make \
   $$PWD/build/examples/CMakeFiles/window.dir/link.txt \
   $$PWD/build/examples/CMakeFiles/window.dir/progress.make \
   $$PWD/build/examples/CMakeFiles/window.dir/window.cpp.o.d \
   $$PWD/build/examples/CMakeFiles/CMakeDirectoryInformation.cmake \
   $$PWD/build/examples/CMakeFiles/progress.marks \
   $$PWD/build/examples/cmake_install.cmake \
   $$PWD/build/tests/CMakeFiles/all_tests.dir/build.make \
   $$PWD/build/tests/CMakeFiles/all_tests.dir/cmake_clean.cmake \
   $$PWD/build/tests/CMakeFiles/all_tests.dir/compiler_depend.make \
   $$PWD/build/tests/CMakeFiles/all_tests.dir/compiler_depend.ts \
   $$PWD/build/tests/CMakeFiles/all_tests.dir/depend.make \
   $$PWD/build/tests/CMakeFiles/all_tests.dir/DependInfo.cmake \
   $$PWD/build/tests/CMakeFiles/all_tests.dir/flags.make \
   $$PWD/build/tests/CMakeFiles/all_tests.dir/link.txt \
   $$PWD/build/tests/CMakeFiles/all_tests.dir/progress.make \
   $$PWD/build/tests/CMakeFiles/dft_test.dir/build.make \
   $$PWD/build/tests/CMakeFiles/dft_test.dir/cmake_clean.cmake \
   $$PWD/build/tests/CMakeFiles/dft_test.dir/compiler_depend.make \
   $$PWD/build/tests/CMakeFiles/dft_test.dir/compiler_depend.ts \
   $$PWD/build/tests/CMakeFiles/dft_test.dir/depend.make \
   $$PWD/build/tests/CMakeFiles/dft_test.dir/DependInfo.cmake \
   $$PWD/build/tests/CMakeFiles/dft_test.dir/dft_test.cpp.o.d \
   $$PWD/build/tests/CMakeFiles/dft_test.dir/flags.make \
   $$PWD/build/tests/CMakeFiles/dft_test.dir/link.txt \
   $$PWD/build/tests/CMakeFiles/dft_test.dir/progress.make \
   $$PWD/build/tests/CMakeFiles/generate_data.dir/build.make \
   $$PWD/build/tests/CMakeFiles/generate_data.dir/cmake_clean.cmake \
   $$PWD/build/tests/CMakeFiles/generate_data.dir/compiler_depend.make \
   $$PWD/build/tests/CMakeFiles/generate_data.dir/compiler_depend.ts \
   $$PWD/build/tests/CMakeFiles/generate_data.dir/depend.make \
   $$PWD/build/tests/CMakeFiles/generate_data.dir/DependInfo.cmake \
   $$PWD/build/tests/CMakeFiles/generate_data.dir/flags.make \
   $$PWD/build/tests/CMakeFiles/generate_data.dir/generate_data.cpp.o.d \
   $$PWD/build/tests/CMakeFiles/generate_data.dir/link.txt \
   $$PWD/build/tests/CMakeFiles/generate_data.dir/progress.make \
   $$PWD/build/tests/CMakeFiles/CMakeDirectoryInformation.cmake \
   $$PWD/build/tests/CMakeFiles/progress.marks \
   $$PWD/build/tests/cmake_install.cmake \
   $$PWD/build/tests/CTestTestfile.cmake \
   $$PWD/build/tools/CMakeFiles/ebu_test.dir/build.make \
   $$PWD/build/tools/CMakeFiles/ebu_test.dir/cmake_clean.cmake \
   $$PWD/build/tools/CMakeFiles/ebu_test.dir/compiler_depend.make \
   $$PWD/build/tools/CMakeFiles/ebu_test.dir/compiler_depend.ts \
   $$PWD/build/tools/CMakeFiles/ebu_test.dir/depend.make \
   $$PWD/build/tools/CMakeFiles/ebu_test.dir/DependInfo.cmake \
   $$PWD/build/tools/CMakeFiles/ebu_test.dir/flags.make \
   $$PWD/build/tools/CMakeFiles/ebu_test.dir/link.txt \
   $$PWD/build/tools/CMakeFiles/ebu_test.dir/progress.make \
   $$PWD/build/tools/CMakeFiles/sample_rate_converter.dir/build.make \
   $$PWD/build/tools/CMakeFiles/sample_rate_converter.dir/cmake_clean.cmake \
   $$PWD/build/tools/CMakeFiles/sample_rate_converter.dir/compiler_depend.make \
   $$PWD/build/tools/CMakeFiles/sample_rate_converter.dir/compiler_depend.ts \
   $$PWD/build/tools/CMakeFiles/sample_rate_converter.dir/depend.make \
   $$PWD/build/tools/CMakeFiles/sample_rate_converter.dir/DependInfo.cmake \
   $$PWD/build/tools/CMakeFiles/sample_rate_converter.dir/flags.make \
   $$PWD/build/tools/CMakeFiles/sample_rate_converter.dir/link.txt \
   $$PWD/build/tools/CMakeFiles/sample_rate_converter.dir/progress.make \
   $$PWD/build/tools/CMakeFiles/CMakeDirectoryInformation.cmake \
   $$PWD/build/tools/CMakeFiles/progress.marks \
   $$PWD/build/tools/cmake_install.cmake \
   $$PWD/build/cmake_install.cmake \
   $$PWD/build/CMakeCache.txt \
   $$PWD/build/libkfr_dft.a \
   $$PWD/build/libkfr_io.a \
   $$PWD/capi/capi.cpp \
   $$PWD/capi/CMakeLists.txt \
   $$PWD/ci/build_capi_win.cmd \
   $$PWD/ci/run.cmd \
   $$PWD/ci/run.sh \
   $$PWD/cmake/aarch64.cmake \
   $$PWD/cmake/arm.cmake \
   $$PWD/cmake/cmake_uninstall.cmake.in \
   $$PWD/cmake/detect_cpu.cpp \
   $$PWD/cmake/ios.cmake \
   $$PWD/cmake/target_set_arch.cmake \
   $$PWD/docs/docs/css/fix.css \
   $$PWD/docs/docs/img/audio_draft_quality.svg \
   $$PWD/docs/docs/img/audio_high_quality.svg \
   $$PWD/docs/docs/img/audio_low_quality.svg \
   $$PWD/docs/docs/img/audio_normal_quality.svg \
   $$PWD/docs/docs/img/biquad_bandpass.svg \
   $$PWD/docs/docs/img/biquad_custom_filter_lowpass.svg \
   $$PWD/docs/docs/img/biquad_filter_lowpass.svg \
   $$PWD/docs/docs/img/biquad_highpass.svg \
   $$PWD/docs/docs/img/biquad_highshelf.svg \
   $$PWD/docs/docs/img/biquad_lowpass.svg \
   $$PWD/docs/docs/img/biquad_lowshelf.svg \
   $$PWD/docs/docs/img/biquad_notch.svg \
   $$PWD/docs/docs/img/biquad_peak.svg \
   $$PWD/docs/docs/img/biquad_peak2.svg \
   $$PWD/docs/docs/img/filtered_noise.svg \
   $$PWD/docs/docs/img/filtered_noise2.svg \
   $$PWD/docs/docs/img/filtered_noise3.svg \
   $$PWD/docs/docs/img/fir_bandpass_kaiser.svg \
   $$PWD/docs/docs/img/fir_bandstop_kaiser.svg \
   $$PWD/docs/docs/img/fir_highpass_kaiser.svg \
   $$PWD/docs/docs/img/fir_lowpass_blackman.svg \
   $$PWD/docs/docs/img/fir_lowpass_hann.svg \
   $$PWD/docs/docs/img/fir_lowpass_kaiser.svg \
   $$PWD/docs/docs/img/noise.svg \
   $$PWD/docs/docs/img/window_bartlett.svg \
   $$PWD/docs/docs/img/window_bartlett_hann.svg \
   $$PWD/docs/docs/img/window_blackman.svg \
   $$PWD/docs/docs/img/window_blackman_harris.svg \
   $$PWD/docs/docs/img/window_bohman.svg \
   $$PWD/docs/docs/img/window_cosine.svg \
   $$PWD/docs/docs/img/window_flattop.svg \
   $$PWD/docs/docs/img/window_gaussian.svg \
   $$PWD/docs/docs/img/window_hamming.svg \
   $$PWD/docs/docs/img/window_hann.svg \
   $$PWD/docs/docs/img/window_kaiser.svg \
   $$PWD/docs/docs/img/window_lanczos.svg \
   $$PWD/docs/docs/img/window_triangular.svg \
   $$PWD/docs/docs/js/math.js \
   $$PWD/docs/docs/bq.md \
   $$PWD/docs/docs/bq_gallery.md \
   $$PWD/docs/docs/conversion.md \
   $$PWD/docs/docs/convert_stereo.md \
   $$PWD/docs/docs/convolution.md \
   $$PWD/docs/docs/dft.md \
   $$PWD/docs/docs/dft2.md \
   $$PWD/docs/docs/dft_format.md \
   $$PWD/docs/docs/ebur128.md \
   $$PWD/docs/docs/expressions.md \
   $$PWD/docs/docs/file_support.md \
   $$PWD/docs/docs/fir.md \
   $$PWD/docs/docs/fir_gallery.md \
   $$PWD/docs/docs/index.md \
   $$PWD/docs/docs/normalize.md \
   $$PWD/docs/docs/plot.md \
   $$PWD/docs/docs/read_audio.md \
   $$PWD/docs/docs/src.md \
   $$PWD/docs/docs/src_gallery.md \
   $$PWD/docs/docs/types.md \
   $$PWD/docs/cxxdox.yml \
   $$PWD/docs/mkdocs.yml \
   $$PWD/dspplot/dspplot/__init__.py \
   $$PWD/dspplot/dspplot/dspplotting.py \
   $$PWD/dspplot/setup.py \
   $$PWD/examples/biquads.cpp \
   $$PWD/examples/ccv.cpp \
   $$PWD/examples/CMakeLists.txt \
   $$PWD/examples/dft.cpp \
   $$PWD/examples/fir.cpp \
   $$PWD/examples/iir.cpp \
   $$PWD/examples/sample_rate_conversion.cpp \
   $$PWD/examples/window.cpp \
   $$PWD/img/biquad.svg \
   $$PWD/img/composite_double_18_119.png \
   $$PWD/img/composite_float_18_119.png \
   $$PWD/img/extra_double_120_30720000.png \
   $$PWD/img/extra_float_120_30720000.png \
   $$PWD/img/fft_performance.png \
   $$PWD/img/KFR.svg \
   $$PWD/img/KFR1.png \
   $$PWD/img/powers2_double_16_16777216.png \
   $$PWD/img/powers2_float_16_16777216.png \
   $$PWD/img/primes_double_17_127.png \
   $$PWD/img/primes_float_17_127.png \
   $$PWD/include/kfr/dft/impl/convolution-impl.cpp \
   $$PWD/include/kfr/dft/impl/dft-impl-f32.cpp \
   $$PWD/include/kfr/dft/impl/dft-impl-f64.cpp \
   $$PWD/include/kfr/dft/impl/fft-impl-f32.cpp \
   $$PWD/include/kfr/dft/impl/fft-impl-f64.cpp \
   $$PWD/include/kfr/dsp/impl/dsp-impl.cpp \
   $$PWD/include/kfr/io/dr/README.txt \
   $$PWD/include/kfr/io/impl/audiofile-impl.cpp \
   $$PWD/tests/cmake/FindGMP.cmake \
   $$PWD/tests/cmake/FindMPFR.cmake \
   $$PWD/tests/data/acos_double_fuzz \
   $$PWD/tests/data/acos_double_narrow \
   $$PWD/tests/data/acos_float_fuzz \
   $$PWD/tests/data/acos_float_narrow \
   $$PWD/tests/data/asin_double_fuzz \
   $$PWD/tests/data/asin_double_narrow \
   $$PWD/tests/data/asin_float_fuzz \
   $$PWD/tests/data/asin_float_narrow \
   $$PWD/tests/data/atan2_double_fuzz \
   $$PWD/tests/data/atan2_double_narrow \
   $$PWD/tests/data/atan2_float_fuzz \
   $$PWD/tests/data/atan2_float_narrow \
   $$PWD/tests/data/atan_double_fuzz \
   $$PWD/tests/data/atan_double_narrow \
   $$PWD/tests/data/atan_float_fuzz \
   $$PWD/tests/data/atan_float_narrow \
   $$PWD/tests/data/cbrt_double_fuzz \
   $$PWD/tests/data/cbrt_double_narrow \
   $$PWD/tests/data/cbrt_float_fuzz \
   $$PWD/tests/data/cbrt_float_narrow \
   $$PWD/tests/data/cos_double_fuzz \
   $$PWD/tests/data/cos_double_narrow \
   $$PWD/tests/data/cos_float_fuzz \
   $$PWD/tests/data/cos_float_narrow \
   $$PWD/tests/data/cosh_double_fuzz \
   $$PWD/tests/data/cosh_double_narrow \
   $$PWD/tests/data/cosh_float_fuzz \
   $$PWD/tests/data/cosh_float_narrow \
   $$PWD/tests/data/coth_double_fuzz \
   $$PWD/tests/data/coth_double_narrow \
   $$PWD/tests/data/coth_float_fuzz \
   $$PWD/tests/data/coth_float_narrow \
   $$PWD/tests/data/exp10_double_fuzz \
   $$PWD/tests/data/exp10_double_narrow \
   $$PWD/tests/data/exp10_float_fuzz \
   $$PWD/tests/data/exp10_float_narrow \
   $$PWD/tests/data/exp2_double_fuzz \
   $$PWD/tests/data/exp2_double_narrow \
   $$PWD/tests/data/exp2_float_fuzz \
   $$PWD/tests/data/exp2_float_narrow \
   $$PWD/tests/data/exp_double_fuzz \
   $$PWD/tests/data/exp_double_narrow \
   $$PWD/tests/data/exp_float_fuzz \
   $$PWD/tests/data/exp_float_narrow \
   $$PWD/tests/data/gamma_double_fuzz \
   $$PWD/tests/data/gamma_double_narrow \
   $$PWD/tests/data/gamma_float_fuzz \
   $$PWD/tests/data/gamma_float_narrow \
   $$PWD/tests/data/log10_double_fuzz \
   $$PWD/tests/data/log10_double_narrow \
   $$PWD/tests/data/log10_float_fuzz \
   $$PWD/tests/data/log10_float_narrow \
   $$PWD/tests/data/log2_double_fuzz \
   $$PWD/tests/data/log2_double_narrow \
   $$PWD/tests/data/log2_float_fuzz \
   $$PWD/tests/data/log2_float_narrow \
   $$PWD/tests/data/log_double_fuzz \
   $$PWD/tests/data/log_double_narrow \
   $$PWD/tests/data/log_float_fuzz \
   $$PWD/tests/data/log_float_narrow \
   $$PWD/tests/data/sin_double_fuzz \
   $$PWD/tests/data/sin_double_narrow \
   $$PWD/tests/data/sin_float_fuzz \
   $$PWD/tests/data/sin_float_narrow \
   $$PWD/tests/data/sinh_double_fuzz \
   $$PWD/tests/data/sinh_double_narrow \
   $$PWD/tests/data/sinh_float_fuzz \
   $$PWD/tests/data/sinh_float_narrow \
   $$PWD/tests/data/tan_double_fuzz \
   $$PWD/tests/data/tan_double_narrow \
   $$PWD/tests/data/tan_float_fuzz \
   $$PWD/tests/data/tan_float_narrow \
   $$PWD/tests/data/tanh_double_fuzz \
   $$PWD/tests/data/tanh_double_narrow \
   $$PWD/tests/data/tanh_float_fuzz \
   $$PWD/tests/data/tanh_float_narrow \
   $$PWD/tests/test-audio/sine.flac \
   $$PWD/tests/test-audio/sine.mp3 \
   $$PWD/tests/unit/base/conversion.cpp \
   $$PWD/tests/unit/base/fraction.cpp \
   $$PWD/tests/unit/base/random.cpp \
   $$PWD/tests/unit/base/reduce.cpp \
   $$PWD/tests/unit/graphics/color.cpp \
   $$PWD/tests/unit/graphics/geometry.cpp \
   $$PWD/tests/unit/math/abs.cpp \
   $$PWD/tests/unit/math/asin_acos.cpp \
   $$PWD/tests/unit/math/atan.cpp \
   $$PWD/tests/unit/math/hyperbolic.cpp \
   $$PWD/tests/unit/math/log_exp.cpp \
   $$PWD/tests/unit/math/min_max.cpp \
   $$PWD/tests/unit/math/round.cpp \
   $$PWD/tests/unit/math/select.cpp \
   $$PWD/tests/unit/math/sin_cos.cpp \
   $$PWD/tests/unit/math/tan.cpp \
   $$PWD/tests/unit/simd/complex.cpp \
   $$PWD/tests/unit/simd/operators.cpp \
   $$PWD/tests/unit/simd/shuffle.cpp \
   $$PWD/tests/unit/simd/vec.cpp \
   $$PWD/tests/all_tests.cpp \
   $$PWD/tests/all_tests_merged.cpp \
   $$PWD/tests/asm_test.cpp \
   $$PWD/tests/base_test.cpp \
   $$PWD/tests/capi_test.cpp \
   $$PWD/tests/CMakeLists.txt \
   $$PWD/tests/complex_test.cpp \
   $$PWD/tests/dft_test.cpp \
   $$PWD/tests/dsp_test.cpp \
   $$PWD/tests/expression_test.cpp \
   $$PWD/tests/generate_data.cpp \
   $$PWD/tests/intrinsic_test.cpp \
   $$PWD/tests/io_test.cpp \
   $$PWD/tests/multiarch.cpp \
   $$PWD/tests/multiarch_fir_avx.cpp \
   $$PWD/tests/multiarch_fir_sse2.cpp \
   $$PWD/tools/CMakeLists.txt \
   $$PWD/tools/ebu_test.cpp \
   $$PWD/tools/sample_rate_converter.cpp \
   $$PWD/azure-pipelines.yml \
   $$PWD/CHANGELOG.md \
   $$PWD/cmake-format.yaml \
   $$PWD/CMakeLists.txt \
   $$PWD/format-all.py \
   $$PWD/LICENSE.txt \
   $$PWD/README.md \
   $$PWD/README_SQUAREDESK.txt \
   $$PWD/sources.cmake

INCLUDEPATH = \
    $$PWD/build-qpdf-Desktop_Qt_5_9_1_clang_64bit-Debug/pdfviewer \
    $$PWD/build-qpdf-Desktop_Qt_5_9_1_clang_64bit-Debug/qpdflib \
    $$PWD/build-qpdfjs-Desktop_Qt_5_9_1_clang_64bit-Debug/debug \
    $$PWD/html-tidy/experimental \
    $$PWD/html-tidy/include \
    $$PWD/html-tidy/src \
    $$PWD/build \
    $$PWD/include/kfr \
    $$PWD/include/kfr/io/dr \
    $$PWD/include/kfr/simd/impl

#DEFINES = 
